alias push='git publish'
alias pull='git pull'
alias ts='tig status'
alias pr='gh pr create'
alias gcb='git checkout -b'
alias gcm='git checkout main'
alias gcma='git checkout master'
alias gcp='git checkout production'
alias clone='gh repo clone'
alias git-track='function _gittrack(){ git branch --set-upstream-to=origin/"$1" "$1";};_gittrack'
alias c='clear'
alias m='python manage.py'
alias emberts='ember t -s --filter $1'
alias eft='ember exam --split=2 --parallel --silent'
